title: STCM140
description: Multimedia production for strategic communications
baseurl: "/class"
url: "https://jamditis.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - README.md
  - LICENSE
